dist: xenial

# blocklist
branches:
  except:
  - gh-pages

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - docker

env:
  global:
    - TMPDIR=/tmp
    - ARCH=amd64
    - CATTLE_HELM_UNITTEST_VERSION=v0.1.6-rancher1

install:
  - curl -L https://git.io/get_helm.sh | bash -s -- -v v3.1.2
  - curl -sSL -o /tmp/ct.tgz https://github.com/helm/chart-testing/releases/download/v3.0.0-beta.2/chart-testing_3.0.0-beta.2_linux_amd64.tar.gz
  - tar xzf /tmp/ct.tgz -C /tmp && sudo cp /tmp/ct /usr/local/bin/ct && command -v ct

script:
  - make

deploy:
  - provider: pages
    token: ${GITHUB_TOKEN}
    target_branch: gh-pages
    local_dir: repo
    skip_cleanup: true
    keep_history: true
