apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: kube-nightwatch
data:
  alert-rules.yaml: |-
    groups:
      - name: Deployment
        rules:
        - alert: Deployment at 0 Replicas
          annotations:
            summary: Deployment {{$labels.deployment}} in {{$labels.exported_namespace}} is currently having no pods running
          expr: |
            sum(kube_deployment_status_replicas) by (deployment,exported_namespace)  < 1
          for: 1m
          labels:
            team: node
      - name: Pods
        rules:
        - alert: Container restarted
          annotations:
            summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.exported_namespace}} was restarted
          expr: |
            sum(increase(kube_pod_container_status_restarts_total[1m])) by (pod,exported_namespace,container) > 0
          for: 0m
          labels:
            team: node