apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: dev-nightwatch
type: Opaque
data:
  thanos.yaml: | # minio_bucket.yaml
    type: s3
    config:
      bucket: thanos # bucket 名称
      endpoint: minio.default.svc.cluster.local:9000 # minio 访问地址
      access_key: minio
      secret_key: minio123
      insecure: true
      signature_version2: false

  